const pgs=[
{id:1,name:'Green Nest Residency',gender:'men',area:'Koramangala',address:'5th Block, Koramangala, Bengaluru',lat:12.9345,lng:77.6147,owner:'Arun Kumar',phone:'+91 90000 10001',rent:{single:18000,double:11000,triple:8500,four:7000},advance:20000,food:'Breakfast + Dinner',facilities:['Wi-Fi','Food','Laundry','AC','Power backup'],img:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80'},
{id:2,name:'Sakhi Women’s Stay',gender:'women',area:'HSR Layout',address:'27th Main, HSR Layout, Bengaluru',lat:12.9116,lng:77.6389,owner:'Priya Rao',phone:'+91 90000 10002',rent:{single:17000,double:10500,triple:8000,four:6800},advance:15000,food:'Breakfast + Dinner',facilities:['Wi-Fi','Food','Security','Laundry','CCTV'],img:'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80'},
{id:3,name:'Urban Hive PG',gender:'men',area:'BTM Layout',address:'2nd Stage, BTM Layout, Bengaluru',lat:12.9166,lng:77.6101,owner:'Ramesh Shetty',phone:'+91 90000 10003',rent:{single:15000,double:9500,triple:7500,four:6200},advance:12000,food:'All meals',facilities:['Wi-Fi','Food','Gym','TV','Parking'],img:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'},
{id:4,name:'Whitefield Comforts',gender:'women',area:'Whitefield',address:'ITPL Main Road, Whitefield, Bengaluru',lat:12.9698,lng:77.7500,owner:'Meena Joseph',phone:'+91 90000 10004',rent:{single:19000,double:12000,triple:9000,four:7200},advance:20000,food:'Breakfast + Dinner',facilities:['Wi-Fi','Food','AC','CCTV','Housekeeping'],img:'https://images.unsplash.com/photo-1560185127-6a8c3e5f7d5d?auto=format&fit=crop&w=900&q=80'},
{id:5,name:'Marathahalli Living',gender:'men',area:'Marathahalli',address:'Outer Ring Road, Marathahalli, Bengaluru',lat:12.9591,lng:77.6974,owner:'Vijay B',phone:'+91 90000 10005',rent:{single:14000,double:9000,triple:7000,four:5800},advance:10000,food:'Breakfast + Dinner',facilities:['Wi-Fi','Food','Laundry','Parking'],img:'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=80'},
{id:6,name:'Electronic City Nest',gender:'women',area:'Electronic City',address:'Phase 1, Electronic City, Bengaluru',lat:12.8452,lng:77.6602,owner:'Anitha M',phone:'+91 90000 10006',rent:{single:13000,double:8500,triple:6800,four:5600},advance:10000,food:'All meals',facilities:['Wi-Fi','Food','Security','Laundry'],img:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80'}
];
const $=id=>document.getElementById(id);
function money(n){return '₹'+n.toLocaleString('en-IN')}
function card(p){return `<article class="pg-card"><div class="pg-image"><img src="${p.img}" alt="${p.name} room"><span class="tag">${p.gender==='men'?'MEN':'WOMEN'}</span><span class="verified">✓ Listed</span></div><div class="pg-body"><h3 class="pg-title">${p.name}</h3><div class="location">⌖ ${p.area} · ${p.address}</div><div class="price-grid"><div class="price"><small>Single / month</small><strong>${money(p.rent.single)}</strong></div><div class="price"><small>Double / month</small><strong>${money(p.rent.double)}</strong></div><div class="price"><small>Triple / month</small><strong>${money(p.rent.triple)}</strong></div><div class="price"><small>4 sharing / month</small><strong>${money(p.rent.four)}</strong></div></div><div class="facilities">${p.facilities.map(x=>`<span class="facility">${x}</span>`).join('')}</div><div class="meta"><div>Food<strong>${p.food}</strong></div><div>Advance<strong>${money(p.advance)}</strong></div><div>Owner<strong>${p.owner}</strong></div><div>Contact<strong>${p.phone}</strong></div></div><div class="card-actions"><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.address)}" target="_blank" rel="noopener">View on Maps ↗</a><button onclick="selectPG(${p.id})">View details</button></div></div></article>`}
function filter(){const q=$('searchInput').value.toLowerCase().trim(),gender=$('genderFilter').value,sharing=$('sharingFilter').value,area=$('areaFilter').value,max=+$('priceFilter').value,food=$('foodFilter').checked,wifi=$('wifiFilter').checked,laundry=$('laundryFilter').checked;const data=pgs.filter(p=>(!q||(p.name+' '+p.area+' '+p.address).toLowerCase().includes(q))&&(gender==='all'||p.gender===gender)&&(area==='all'||p.area===area)&&(sharing==='all'||p.rent[sharing]<=max)&&(sharing==='all'||p.rent.single<=max)&&(food?p.facilities.includes('Food'):true)&&(wifi?p.facilities.includes('Wi-Fi'):true)&&(laundry?p.facilities.includes('Laundry'):true));$('listingGrid').innerHTML=data.length?data.map(card).join(''):`<div class="empty"><h3>No PGs found</h3><p>Try a different area, sharing type or budget.</p></div>`;$('resultCount').textContent=`${data.length} PG${data.length!==1?'s':''} found`}
function selectPG(id){const p=pgs.find(x=>x.id===id);$('selectedPlace').innerHTML=`<strong>${p.name}</strong><br>${p.address}<br><small>Owner: ${p.owner} · Advance: ${money(p.advance)}</small>`;$('mapsLink').href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.address)}`;$('mapFrame').innerHTML=`<iframe title="${p.name} Google Maps" width="100%" height="100%" style="border:0;min-height:560px" loading="lazy" src="https://www.google.com/maps?q=${encodeURIComponent(p.address)}&output=embed"></iframe>`;document.getElementById('map').scrollIntoView({behavior:'smooth'})}
['searchInput','genderFilter','sharingFilter','areaFilter','foodFilter','wifiFilter','laundryFilter'].forEach(id=>$(id).addEventListener('input',filter));$('searchBtn').addEventListener('click',filter);$('priceFilter').addEventListener('input',()=>{$('priceOutput').textContent=money(+$('priceFilter').value);filter()});$('resetBtn').addEventListener('click',()=>{['searchInput'].forEach(id=>$(id).value='');$('genderFilter').value='all';$('sharingFilter').value='all';$('areaFilter').value='all';$('priceFilter').value=30000;$('priceOutput').textContent='₹30,000';['foodFilter','wifiFilter','laundryFilter'].forEach(id=>$(id).checked=false);filter()});filter();
